### ISSUE TITLE
It is not possible to use a generic action with ash_json_api

### ISSUE THREAD

**Issue by user20230119** [ash-project/ash_json_api#105]
**Is your feature request related to a problem? Please describe.**
Right now it is not possible to use a generic action with `ash_json_api` unfortunately

**Describe the solution you'd like**
Add a warning in the docs that it is not possible to use a generic action with `ash_json_api` unfortunately
https://hexdocs.pm/ash_json_api/getting-started-with-json-api.html

**Describe alternatives you've considered**
You would need to make your own route/controller and call the action, and pass the result into our serializer

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

Right now it is not possible to use a generic action with `ash_json_api` unfortunately

**Additional context**
https://discord.com/channels/711271361523351632/711271361523351636/1162969517845118976
![image](https://github.com/ash-project/ash_json_api/assets/123089799/5eb4dbe7-294a-4970-a760-35a0343315e2)

**Comment by zachdaniel** [comment]
This has been added in main of `ash_json_api`.
