### ISSUE TITLE
Inconsistency between hex code and hexdocs

### ISSUE THREAD

**Issue by m0rt3nlund** [ash-project/ash_json_api#106]
**Describe the bug**
I think a newer version of the hexdocs are available than the code.
The DSL for AshJsonApi.Resource includes "include_nil_values" in hexdocs, but version 0.33.1 code does not.
https://hexdocs.pm/ash_json_api/AshJsonApi.Resource.Info.html#include_nil_values?/1
https://github.com/ash-project/ash_json_api/blob/v0.33.1/lib/ash_json_api/resource/info.ex#L1

**To Reproduce**
Visit the provided URLs

**Expected behavior**
The DSL properties to exist

** Runtime
 - Ash JSON API version 0.33.1

**Comment by zachdaniel** [comment]
You are correct, I published the hexdocs with new changes. Sorry about that. Will publish a new version.
