### ISSUE TITLE
Missing links for related relationship data

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_json_api#168]
**Describe the bug**

The example for [compound documents](https://jsonapi.org/format/#document-compound-documents) and [relationships](https://jsonapi.org/format/#document-resource-object-relationships) in the JSON:API docs show that we should be providing links for how to fetch related data, if they exist.

eg. 
* a `relationship` route should appear as a `self` route in the links
* a `related` route should appear as a `related` route in the links

This is important for discoverability of relationships in the API.

**To Reproduce**

For an `Artist` resource defined like so:

```elixir
  json_api do
    type "artist"

    routes do
      base "/artists"
      get :read
      related :albums, :read
    end
  end
```

An API response to get an artist returns the following relationship data:

```json
    "relationships": {
      "albums": {
        "links": {},
        "meta": {}
      }
    }
```

**Expected behavior**

I would expect the `links` in the relationship data to include a `related` link like:

```json
{
  "links": {
    "related": "http://localhost:4000/api/artists/the_artist_id/albums"
  }
}
```

In a similar/related vein, I'd expect the `links` for `included` resources to be populated with `self` links.

**Runtime**

- Elixir version 1.17.0-otp-27
- Erlang version 27.0
- OS macOS Sonoma
- Ash version 3.0.12
- AshJsonApi version main branch at commit https://github.com/ash-project/ash_json_api/commit/0bbdd179fa9fe06d78f5881fd02b03ebfeeee747

**Comment by zachdaniel** [comment]
Alright, so this one was primarily a documentation issue. I've added a *very* high level guide for this, as I'm a bit low on time today. It does, however, explain that links are generated from `primary?` routes. So to have your links generated, you'd want to designate the appropriate routes as `primary? true`

**Comment by sevenseacat** [comment]
I didn't even know that was an option! cheers 👍
