### ISSUE TITLE
Enum types are exposed as object in openapi spec

### ISSUE THREAD

**Issue by olivermt** [ash-project/ash_json_api#176]
**Describe the bug**
```
defmodule SomeType do
  use Ash.Type.Enum, values: [foo: "foo", bar: "bar"]
end
```
This ends up in openapi as:
```
{
        "additionalProp1": {}
      },
```

**To Reproduce**
Just make any kind of enum, either with `:atom, constrains: [one_of: [...]]` or with the included Ash.Type.Enum sample

**Expected behavior**
Be exposed as swagger enums: https://swagger.io/docs/specification/data-models/enums/

** Runtime
 - Ash version: 3.0.21
 - Jsonapi version: 1.2.1

**Comment by zachdaniel** [comment]
I've made two changes: 1. it will now properly render enums since that was low hanging fruit, and 2. unknown types now properly show as "any" instead of "object".
