### ISSUE TITLE
Embedded resource shows up as generic attribute of JSON map

### ISSUE THREAD

**Issue by olivermt** [ash-project/ash_json_api#180]
**Describe the bug**
Adding an action mapping with an `accepts [:location]` where `location` is am embed shows a generic JSON object input:
```
{
  "data": {
    "attributes": {
      "location": {
        "additionalProp1": {}
      }
    },
    "id": "string",
    "relationships": {},
    "type": "cesium_asset"
  }
}
```

**Expected behavior**
Embedded should show up as a nested json structure in the openapi spec

**Comment by zachdaniel** [comment]
Completed in 7e25b92b8bf78b22b2736ff1093eb6de698a4313
