### ISSUE TITLE
Don't require update action on embedded if no update routes are present

### ISSUE THREAD

**Issue by rbino** [ash-project/ash_json_api#197]
**Describe the bug**
After 7e25b92b8bf78b22 we had a small regression where we add an `:update` action to an embedded resource that was used as an argument even if the parent resource only had a single route with a `:create` action (so it was never used in `:update` actions via JSON:API)

**Expected behavior**
Update actions should be required (and their doc generated) only if they are actually used

**Comment by zachdaniel** [comment]
What happens in that case? Do you get an error?
