### ISSUE TITLE
Igniter tasks don't wrap modules in `Module.concat` hack when adding to domain

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_json_api#213]
**Describe the bug**

Not technically a *bug*, but behaviour changed from existing documentation. Currently we say this for manual installs:

<img width="866" alt="Screenshot 2024-07-27 at 1 38 14 AM" src="https://github.com/user-attachments/assets/1cdd491d-c5ec-4335-931c-d2630fbe3296">

But when we add domains to a JsonApiRouter via an igniter like `ash.patch.extend`, we don't have the `Module.concat` hack in place, it lists the domains normally.

```
Update: lib/cat_web/ash_json_api_router.ex

1 1   |defmodule CatWeb.AshJsonApiRouter do
2 2   |  use AshJsonApi.Router,
3   - |    domains: [],
  3 + |    domains: [Cat.Food],
4 4   |    open_api: "/open_api"
5 5   |end
   ...|
```

**Runtime**

 - Elixir version 1.17.2-otp-27
 - Erlang version 27.0.1
 - OS macOS Sonoma
 - Ash version 3.2.6
 - AshJsonApi version 1.3.8

**Comment by zachdaniel** [comment]
Fixed in f4a4f301ea61b51dba7b9f61ef8ae1b90ccaffcf
