### ISSUE TITLE
Igniter setup multipart parser

### ISSUE THREAD

**Issue by maennchen** [ash-project/ash_json_api#218]
**Is your feature request related to a problem? Please describe.**

WIth #214, a parser needs to be added to the `Plug.Parser` config in the endpoint.

**Describe the solution you'd like**

Add the parser.

**Describe alternatives you've considered**

None

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

```elixir
plug Plug.Parsers,
  #                                         V====================V
  parsers: [:urlencoded, :multipart, :json, AshJsonApi.Plug.Parser],
  pass: ["*/*"],
  json_decoder: Jason
```

**Additional context**

Continued from #214

**Comment by zachdaniel** [comment]
This has been complete din `main` :)
