### ISSUE TITLE
Support customizing the primary key

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash_json_api#22]
Right now, ash_json_api requires that an `id` field is the primary key. We should be able to support any field being the primary key, and we can also most likely support composite primary keys by stringifying/connecting the values. This only works on types that can be stringified, so that may need to be included in the type behaviour. Potentially, we can just look at the base type of the type and see if it can be stringified.

**Comment by kyle5794** [comment]
Hi @zachdaniel, I'm thinking of picking this up. I wonder why `ash_json_api` must require the primary key? Is it only for the `&default_sort/1`? What do you suggest where I should start?

**Comment by kyle5794** [comment]
Thanks, @zachdaniel. Your detailed explanation is really helpful. I'll start working on this.

**Comment by zachdaniel** [comment]
Closed thanks to great work from @kyle5794
