### ISSUE TITLE
Provide configuration option to opt-out of showing filter schemas in the swagger ui

### ISSUE THREAD

**Issue by briankariuki** [ash-project/ash_json_api#231]
The recent versions of this package introduced additional data into the schemas section in the swagger ui. Specifically, now all attributes have their own filter schema in the ui. While this ok for projects that have very few resources and attributes, for large projects with multiple resources that have 50+ attributes, loading the swagger ui is now very slow and takes a long time. Also these filter schemas are not grouped by resource. See image below.

<img width="864" alt="image" src="https://github.com/user-attachments/assets/d96095ec-7c16-4709-9307-87e62a150627">

A solution is having this feature enabled/disabled via configuration.

For example

```elixir
json_api do
  type "post"
  filter_schema? false  //<---- This for example

  routes do
    base "/posts"

    index :read
    get :read
  end
end
```

**Comment by zachdaniel** [comment]
So, I'm pretty sure the expense here is the generation of the schema. I've pushed a feature that allow you to use a static file to serve your open api schema. You can generate this static file with 

```
mix openapi.spec.json --spec MyAppWeb.AshJsonApiRouter --check
```

Then you can configure it like so:

```
open_api_file =
  if Mix.env() == :prod do
    "priv/static/open_api.json"
  else
    nil
  end

use AshJsonApi.Router,
  domains: [...],
  open_api: "/open_api",
  modify_open_api: {__MODULE__, :modify_open_api, []},
  open_api_file: open_api_file
open_api_file =
  if Mix.env() == :prod do
    "priv/static/open_api.json"
  else
    nil
  end

use AshJsonApi.Router,
  domains: [...],
  open_api: "/open_api",
  modify_open_api: {__MODULE__, :modify_open_api, []},
  open_api_file: open_api_file
```

**Comment by zachdaniel** [comment]
Can you try that out to see if it solves your loading issues? Please reopen if not.

**Comment by briankariuki** [comment]
> Can you try that out to see if it solves your loading issues? Please reopen if not.

I'll try this and report back
