### ISSUE TITLE
`ash_json_api.install` adds a router pipeline for `:api` even if it already exists

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_json_api#234]
**Describe the bug**

The default Phoenix router is generated with a `pipeline :api` block already in it. 

When adding AshJsonApi to an existing Phoenix app, Igniter adds *another* `pipeline :api` block to the router, causing an compilation warning:

```
    warning: this clause for api/2 cannot match because a previous clause at line 4 always matches
    │
 17 │   pipeline :api do
    │   ~~~~~~~~~~~~~~~~
    │
    └─ lib/tunez_web/router.ex:17
```

**Expected behavior**

Igniter should not add a `pipeline :api` block if it already exists (and accepts json).

** Runtime
 - Elixir version 1.17.2-otp-27
 - Erlang version 27.0.1
 - OS macOS Sequoia
 - Ash version 3.4.19
 - AshJsonApi version 1.4.8
 - Igniter version 0.3.39

**Comment by zachdaniel** [comment]
Fixed in the latest release of `igniter`.
