### ISSUE TITLE
Allow customization of response status for POST requests

### ISSUE THREAD

**Issue by Fasp96** [ash-project/ash_json_api#241]
**Description:**

I need to modify the response status code from the default 201 to 200 for a specific POST route. Despite trying to use the `modify_conn function`, the status code change doesn't seem to take effect.

**The current approach is as follows:**

```elixir
json_api do
  type "twilio"

  routes do
    base("/twilio")

    route :post, "/token", :generate_token do
      modify_conn fn conn, subject, result, request ->
        conn
        |> Plug.Conn.put_status(200)
      end
    end
  end
end
```
**Expected Behavior:**
The response status for the /token POST route should return 200 instead of 201.

**Actual Behavior:**
The response status remains 201, and the `modify_conn function` does not override it.

**Comment by zachdaniel** [comment]
Hey @Fasp96, addressed in `main`, mind trying it out?

**Comment by Fasp96** [comment]
It work! 🙌 Thank you @zachdaniel

**Comment by Fasp96** [comment]
Just wondering, any idea when the next release will be out? It seems like this is the only change since the last version, so curious if it'll happen soon.

**Comment by zachdaniel** [comment]
I'll cut one now

**Comment by Fasp96** [comment]
Thank you
