### ISSUE TITLE
Missing naive_datetime Translation in OpenApi Spex Generation

### ISSUE THREAD

**Issue by Fasp96** [ash-project/ash_json_api#244]
**Description:**
When generating the OpenAPI specification using OpenApi Spex, I encountered an issue where the `naive_datetime` type in an Ash action argument is not properly translated into the OpenAPI spec. This results in the field being generated without a type or format, essentially defaulting to `"any"`.

Here's an example of the action definition:

```elixir
create :create_from_form do
  argument :campaign_id, :uuid, allow_nil?: false
  argument :file_id, :uuid, allow_nil?: false
  argument :language, :string, allow_nil?: false
  argument :first_name, :string, allow_nil?: false
  argument :last_name, :string, allow_nil?: false
  argument :phone, :string, allow_nil?: false
  argument :schedule_call_memo, :string, allow_nil?: false
  argument :schedule_call_datetime, :naive_datetime, allow_nil?: false
end
```

However, the generated OpenAPI spec for `schedule_call_datetime` is missing its type/format:

```json
"properties": {
  "campaign_id": {
    "format": "uuid",
    "type": "string"
  },
  "file_id": {
    "format": "uuid",
    "type": "string"
  },
  "first_name": {
    "type": "string"
  },
  "language": {
    "type": "string"
  },
  "last_name": {
    "type": "string"
  },
  "phone": {
    "type": "string"
  },
  "schedule_call_datetime": {},
  "schedule_call_memo": {
    "type": "string"
  }
}
```

It looks like the naive_datetime type isn't being properly handled during the OpenAPI generation process. I was expecting it to be translated into a standard `datetime` format.

**Expected Behavior:**
The `schedule_call_datetime` field should be properly typed as a `datetime` field in the generated OpenAPI spec.

**Comment by Fasp96** [comment]
Any idea when the next release will be out?

**Comment by zachdaniel** [comment]
just now
