### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by andrewcallahan** [ash-project/ash_json_api#25]
**Describe the bug**
I'm getting a compile error
```
== Compilation error in file lib/ash_json_api/test.ex ==
** (File.Error) could not read file "test/support/response_schema": no such file or directory
    (elixir 1.10.2) lib/file.ex:353: File.read!/1
    lib/ash_json_api/test.ex:10: (module)
    (stdlib 3.12) erl_eval.erl:680: :erl_eval.do_apply/6
could not compile dependency :ash_json_api, "mix compile" failed. You can recompile this dependency with "mix deps.compile ash_json_api", update it with "mix deps.update ash_json_api" or clean it with "mix deps.clean ash_json_api"
```

**To Reproduce**
run `iex -S mix phx.server`

**Expected behavior**
I expect my application to compile

** Runtime
 - Elixir version: 1.10.2
 - Erlang version: OTP/22
 - OS: Mac OS
 - Ash version: 0.3.0
 - any related extension versions: AshJsonApi: 0.1.4, AshPostgres 0.1.4

**Additional context**
N/A

**Comment by zachdaniel** [comment]
Need to specify the required file in the hex package files.

**Comment by zachdaniel** [comment]
This was resolved in https://github.com/ash-project/ash_json_api/commit/420ed8b113c3ba7b1e9cbab4ddb87bd4209a5e82
