### ISSUE TITLE
GET routes of a generic action return no id fields even if they are public

### ISSUE THREAD

**Issue by diogomrts** [ash-project/ash_json_api#263]
**Description**
When setting up a GET route on a generic action, the resource's id is omitted from the response.

**To Reproduce**
In this example Resource you can see the issue:

```elixir
defmodule TestRepo.Domain.Generic do
  use Ash.Resource,
    domain: TestRepo.Domain,
    extensions: [AshJsonApi.Resource]

  json_api do
    type("generic")

    routes do
      base "/generic"
      route(:get, "", :create)
    end
  end

  actions do
    action :create, {:array, :struct }do
      constraints items: [instance_of: __MODULE__]

      run fn input, context ->
        {:ok, [%__MODULE__{
          id: 1,
          name: "name"
        }]}
      end
    end
  end

  attributes do
    integer_primary_key(:id, writable?: true, public?: true)
    # attribute(:id, :integer, primary_key?: true, allow_nil?: false, public?: true)
    attribute(:name, :string, public?: true)
  end
end
```

The response JSON is:

```json
[
  {
    "name": "name"
  }
]
```

**Expected behavior**
The expected response should be:
```json
[
  {
    "id": 1,
    "name": "name"
  }
]
```

**Comment by zachdaniel** [comment]
Took me a while to get to this. I looked a the code thinking it would be relatively simple, but I don't see where we are for some reason omitting that id. Could you please put together a test or a reproduction?

**Comment by diogomrts** [comment]
I have added to this test_repo, please take a look at the `Generic` resource's `/v1/generic` endpoint

![image](https://github.com/user-attachments/assets/d91be1af-18c0-404b-9d10-a631625c596c)
