### ISSUE TITLE
Support Date Type

### ISSUE THREAD

**Issue by andrewcallahan** [ash-project/ash_json_api#27]
**Is your feature request related to a problem? Please describe.**
I can't support date types that are used in Ash

**Describe the solution you'd like**
I'd like to be able to use dates in Ash JSON:API. I would expect that dates would be serialized and deserialized in the YYYY-MM-DD format.

**Describe alternatives you've considered**
N/A

**Express the feature either with a change to resource syntax, or with a change to the resource interface**
N/A

**Additional context**
N/A

**Comment by zachdaniel** [comment]
This is done.
