### ISSUE TITLE
Validate filter fields

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash_json_api#33]
Right now, we don't validate that filters/sorts only use the fields exposed in the json api, which would be a big problem if someone used this in production (if anyone is reading this issue, and ash is still in alpha, and you used it in production and somehow exposed some data about your system, it is your fault :) )

**Comment by kyle5794** [comment]
Hi @zachdaniel, I think I could pick this up. Could you elaborate more on fields/sorts that we need to validate?

**Comment by zachdaniel** [comment]
Hey @kyle5794 I think this would be a great one to pick up :) There are actually a few concerns worth considering here:

The fact that this is even necessary *could* imply that we're missing something else or that there is a design issue. Specifically, I'm not so sure that having resources that expose different attributes over different APIs really embodies the design of Ash. I haven't fully come to a conclusion on this one, so it would be great to get your perspective.

Some alternatives:

## Separate Resources

The most straightforward would be to simply suggest decoupling the API resource from the underlying resource. I'm still working on this, but the goal is to not *require* that resources are hard coupled to the data layer. Specifically, we'll want to be able to declare resources that simply interact with other resources. If you have different information to show in your API than you do on the resource itself, it could imply that you're really talking about *two* resources.

That might look something like this:
```elixir
defmodule MyApp.External.MyResource do
 ...
end

defmodule MyApp.MyResource do
  ...
end
```

## Action level configuration

Embed the fields that are returned at the action level, e.g
```
actions do
  read :read, loadable: [...]

  create :create, loadable: [...]
end
```

This still requires a lot of code to ensure that filters/sorts aren't used on queries that don't honor that `loadable` (or whatever we call it) rule.

## Wrap up
Ultimately, I don't think we want to be in the business of requiring that every extension be capable of slicing and dicing the behavior of a resource that they are working with. Ultimately that would make *every* extension share all of that same logic.

What do you think?

**Comment by kyle5794** [comment]
> ### **Separate Resources**

This definitely reminds me of the `customer` and `representative` resources in `ash_example` where they both have `users` as the data source but have different API so I think simply having separated resources for different API seems very natural with how ash resource is.

> ### **Action level configuration**

I think this one could allow a degree of flexibility on how users want to define their API. I don't think it's crazy that two APIs in the same resources might require slightly different responses fields (it might not be common tho) which makes action level configuration seems to be a nice thing to have. However, I'm unsure that being too flexible would be a good thing or not

**Comment by zachdaniel** [comment]
Yeah, it will be a difficult balance. We want to be flexible, but in such a way as to not let people footgun themselves. I think what we might want to talk about at this point is how do we go about making it easy to "base" resources off of other resources. I think that some out of the box thinking could go a long way here. For example, we could support "importing" explicit configuration from other resources.

```
defmodule Helpdesk.Tickets.Representative do
  use Ash.Resource,
    ...

  import_section :postgres

  import_section :attributes, only: [:id, :first_name, :last_name]

  ...
end
```

The case could also be made that resources are just "simple enough" to not need this kind of indirection to support multiple resources that point at the same storage.

**Comment by kyle5794** [comment]
In this case, I think we might want a new section that looks like this
```
defmodule Helpdesk.Tickets.Representative do
  use Ash.Resource,

......

import_from do
    source Helpdesk.Accounts.User
    section :postgres
    section :attributes, only: [:first_name, :last_name]
    section [:json_api, :routes], except: [:get, :index]
end
```

However, because of the issue chains, this one -> #8 -> #36, I havent understood the main points and the big picture of what we want to achieve yet. Could you explain how all of the issues are linked to each other?

**Comment by zachdaniel** [comment]
I'm not sure #36 is involved.  

Ultimately it is a general design question. "if you have to limit the resources that appear from your (ash) api, or the attributes that appear in a resource, then perhaps you really ought to have *separate* apis/resources". The point of resources are that they are supposed to be interfaces that can be used over many mediums, e.g you can get a code-api/json api/graphql all from one resource. But if you're saying "the json API has x attributes, the graphql has y attributes, and the code-api has z attributes", then are you really exposing *one* interface? Or are you hiding 3 interfaces in one?

**Comment by zachdaniel** [comment]
So I think the real answer here may actually be to *just remove* the `fields` options in graphql and json:API. And perhaps we can examine the next practical use case someone has for slicing and dicing the fields that are exposed, and go from there.

**Comment by kyle5794** [comment]
> I'm not sure #36 is involved.

Sorry. I linked the wrong issue, it should be ash-project/ash#36 which is mentioned in #8 

> But if you're saying "the json API has x attributes, the graphql has y attributes, and the code-api has z attributes", then are you really exposing one interface? Or are you hiding 3 interfaces in one?

I think this point really helps clear up. If I understand correctly, from a design point of view, if we want to group a code-api/json-api/graphql into one resource, their behaviours/properties must somewhat agree with each other. In this case, even though the `fields` option provides flexibility, it might create inconsistent behaviours between resources.

**Comment by zachdaniel** [comment]
Exactly. In many cases, the resource/code interface need to be aware of certain attributes that shouldn't be exposed by any other API, so what I think we may want to do is add an option to attributes like `private?: true`. This matters because a resource will likely end up composing some set of private properties into calculations/custom filters (when we have them), that kind of thing. Then we want to cut a good balance between making it possible for usage of the code API to not care that some attributes are private, while usage from extensions doesn't/can't see those attributes.

The technical feasibility of that last part is difficult though. We may just need to accept the fact that we have to add code to each extension to ignore private attributes. E.g adding things like `Ash.Query.public()` and `Ash.Changeset.public()`, which set something internally to express that the internals need to switch from `Ash.Resource.attribute/2` to a new `Ash.Resource.public_attribute/2`.

We could eventually support this w/ relationships too.

**Comment by zachdaniel** [comment]
So far, I've seen that you have to be okay with making some exceptions for the code interface, so I don't think this is a big deal.

**Comment by zachdaniel** [comment]
@kyle5794 if you want to try out just *removing* the `fields` parameter, I think thats a good first step.

**Comment by kyle5794** [comment]
@zachdaniel sounds good to me. I'll work on it

**Comment by zachdaniel** [comment]
@kyle5794 the next steps
Would be to 1.) remove `fields` from ash_GraphQL and then 2.) add a `private?: true` flag for attributes and relationships, and then switch the extensions to only get attributes and relationships via `public_attributes` and `public_relationships` (or something along those lines)

**Comment by kyle5794** [comment]
@zachdaniel I'll start with 2.) in ash_json_api first then move to ash_graphql

**Comment by zachdaniel** [comment]
🧠 smart plan.

**Comment by zachdaniel** [comment]
This has been completed!
