### ISSUE TITLE
filtering by some integer value is not possible

### ISSUE THREAD

**Issue by peillis** [ash-project/ash_json_api#52]
Consider for example an url like `/device_screens?filter[screen_id]=12`, it gives the following error:

```json
{
    "errors": [
        {
            "code": "InvalidQuery",
            "detail": "Expected \"integer\", got \"1\", at [\"filter\", \"screen_id\"].",
            "id": "c4c36828-785f-4317-b662-2371abcf95a6",
            "source": {
                "parameter": "filter[screen_id]"
            },
            "status": 400,
            "title": "Invalid Query"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}
```

**Comment by zachdaniel** [comment]
Ah, yeah that is no good. If you want to try this out and PR it if it resolves the issue, I'd be grateful:
https://github.com/ash-project/ash_json_api/blob/master/lib/ash_json_api/json_schema/json_schema.ex#L325

We can change those `"type" => "integer"`

Something like this:
```elixir
%{
  "type" => ["integer", "string"],
  "match" => "^[1-9][0-9]*$"
}
```

And for boolean

```elixir
%{
  "type" => ["boolean", "string"]
  "match" => "^(true|false)$"
}
```

THat might not be exactly right, but it is the gist of it.

**Comment by peillis** [comment]
Yeah, it works. I already did the PR. Thank you!

**Comment by zachdaniel** [comment]
Awesome, thanks for the report and for contributing the fix!
