### ISSUE TITLE
Support Open API specs (and swagger)

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash_json_api#62]
A natural extension of the declarative nature of Ash is to support open api specs and tools like swagger UI. We've got some groundwork for this in the JsonSchema generation, and we should be able to leverage much of that for Open API 🥳 https://swagger.io/specification/

**Comment by zachdaniel** [comment]
It's still in flight

**Comment by mohammedzeglam-pg** [comment]
> It's still in flight

is there any reference work to begin with it, or help with it.

**Comment by zachdaniel** [comment]
https://github.com/ash-project/ash_json_api/pull/64 This PR needs some testing/linting/cleanup, and then I think it will be good to go :)

**Comment by zachdaniel** [comment]
The first pass at this has been merged! I'm sure there will need to be improvements made in the future, but the (excellent) groundwork is there!
