### ISSUE TITLE
When no `limit` is set on a paginated read action it crashes.

### ISSUE THREAD

**Issue by jimsynz** [ash-project/ash_json_api#81]
<img width="3360" alt="Screenshot 2023-05-12 at 11 30 21 AM" src="https://github.com/ash-project/ash_json_api/assets/59449/37263f86-9bfd-4519-bd7c-b537e38675fd">

**Comment by zachdaniel** [comment]
Some additional context, only happens if there is no `default_limit`.

**Comment by zachdaniel** [comment]
I believe this was fixed a long time ago :)
