### ISSUE TITLE
Query parameter not passed as argument

### ISSUE THREAD

**Issue by martinhrvn** [ash-project/ash_json_api#82]
**Describe the bug**
On mutation the query/path params are not passed as arguments

**To Reproduce**

If we have route with parameter and we use this parameter as argument for mutation action:

```
routes do
  post :for_tracker, route: "/trackers/:tracker_id/option"
end

actions do
  create :for_tracker do
    argument :tracker_id, :string, allow_nil?: false
    ...
  end
end
```
It fails with `Required properties are missing: [\"tracker_id\"]`

**Expected behavior**
A path parameter is passed as argument to the action.

** Runtime
 - Elixir version: 1.14.4
 - Erlang version: 25.3
 - OS: Mac OS
 - Ash version: 2.9.5
 - any related extension versions

**Additional context**
-

**Comment by zachdaniel** [comment]
What we need to do here is add an option to the routes for these to say which path parameters should be used in the create/update/destroy action and which should be used in the lookup.
