### ISSUE TITLE
List query params causes a crash

### ISSUE THREAD

**Issue by gordoneliel** [ash-project/ash_json_api#93]
**Describe the bug**
When filtering with list values eg. `filter[status][in][0]=a&filter[status][in][1]=b`, ash logs an error in the query because it does not handle list params.

**To Reproduce**
Create an enum attribute `status` with values `[:a, :b, :c]`. 
Pass in for filters in a query: `filter[status][in][0]=a&filter[status][in][1]=b`

Ash query will embed an error:
```elixir
  errors: [
    %Ash.Error.Unknown.UnknownError{
      error: "filter: Could not cast expression: Ash.Query.Operator.In status %{\"0\" => \"active\"}",
      field: nil,
      changeset: nil,
      query: nil,
      error_context: [],
      vars: [],
      path: [:filter],
      stacktrace: #Stacktrace<>,
      class: :unknown
    }
  ]
  ```

**Expected behavior**
Should handle list query params and filter

** Runtime
 - Elixir version: 1.15.4
 - Erlang version: 26.0.2
 - OS: macos
 - Ash version: 2.13.2

**Comment by zachdaniel** [comment]
I think I accidentally led you astray on this initially. Try this `filter[status][in][]=a&filter[status][in][]=b`

**Comment by gordoneliel** [comment]
This works, closing!
