### ISSUE TITLE
Resource links use conn url instead of Endpoint url

### ISSUE THREAD

**Issue by gordoneliel** [ash-project/ash_json_api#94]
I'm using a service backed by ash  behind a gateway. When I request a resource, the links generated use the request url instead of the url configured by the endpoint. Ideally I think we should be using 'Endpoint.url()' as the base url for resource links instead of the conn url as links will be incorrect when behind a proxy.

Happy to take this on if it makes sense!

**Comment by zachdaniel** [comment]
That makes perfect sense! Thanks for offering to handle it, look forward to your PR!
